-- MySQL Workbench Synchronization
-- Generated: 2024-04-19 09:21
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Bianca Mesa

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `taylor_swift_db`.`song` 
DROP FOREIGN KEY `fk_song_album`;

ALTER TABLE `taylor_swift_db`.`song` 
CHANGE COLUMN `fk_album_albumId` `fk_albumId` INT(11) NOT NULL ;

ALTER TABLE `taylor_swift_db`.`song` 
ADD CONSTRAINT `fk_song_album`
  FOREIGN KEY (`fk_albumId`)
  REFERENCES `taylor_swift_db`.`album` (`albumId`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
